version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example
      MYSQL_USER: app
      MYSQL_PASSWORD: very_strong
    ports:
      - "3306:3306"
    networks:
      - shvirtd_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  app:
    image: shvirtd-app:latest
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASSWORD: very_strong
      DB_NAME: example
      TABLE_NAME: requests_table
      MYSQL_SSL_MODE: DISABLED
    ports:
      - "5000:5000"
    networks:
      - shvirtd_net
    deploy:
      replicas: 2
      restart_policy:
        condition: any

  haproxy:
    image: haproxy:2.9
    volumes:
      - /app/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8090:8090"
    networks:
      - shvirtd_net
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  shvirtd_net:
    driver: overlay